# Generated by Django 3.1.7 on 2021-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210313_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publicar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='imagen'),
        ),
    ]
