# Generated by Django 3.1.7 on 2021-03-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210315_0012'),
    ]

    operations = [
        migrations.RenameField('category', 'category', 'name'),
    ]
