# Generated by Django 3.1.7 on 2021-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210318_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/categories/', verbose_name='imagen'),
        ),
    ]
